# .pre-commit-config.yaml
# Add this file to your project and install the pre-commit hooks:
#   pre-commit install-hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, master, --branch, main, --branch, beta]
      - id: trailing-whitespace

  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.18
    hooks:
      - id: forbid-binary
      - id: shellcheck
      - id: shfmt
